package dominio.dominio;

// Generated 02-dic-2008 9:49:40 by Hibernate Tools 3.2.2.GA

/**
 * DetalleRecibo generated by hbm2java
 */
public class DetalleRecibo implements java.io.Serializable {

	private int iddetalleRecibo;
	private Recibo recibo;
	private String concepto;
	private double importe;

	public DetalleRecibo() {
	}

	public DetalleRecibo(Recibo recibo, String concepto, double importe) {
		this.recibo = recibo;
		this.concepto = concepto;
		this.importe = importe;
	}

	public int getIddetalleRecibo() {
		return this.iddetalleRecibo;
	}

	public void setIddetalleRecibo(int iddetalleRecibo) {
		this.iddetalleRecibo = iddetalleRecibo;
	}

	public Recibo getRecibo() {
		return this.recibo;
	}

	public void setRecibo(Recibo recibo) {
		this.recibo = recibo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public double getImporte() {
		return this.importe;
	}

	public void setImporte(double importe) {
		this.importe = importe;
	}

}
