package dominio.dominio;

// Generated 08-ene-2009 19:15:20 by Hibernate Tools 3.2.4.CR1

/**
 * DetalleRecibo generated by hbm2java
 */
public class DetalleRecibo implements java.io.Serializable {

	private int iddetalleRecibo;
	private Recibo recibo;
	private String concepto;
	private double importe;
	private String dni;

	public DetalleRecibo() {
	}

	public DetalleRecibo(Recibo recibo, String concepto, double importe,String dni) {
		this.recibo = recibo;
		this.concepto = concepto;
		this.importe = importe;
		this.dni=dni;
	}

	public int getIddetalleRecibo() {
		return this.iddetalleRecibo;
	}

	public void setIddetalleRecibo(int iddetalleRecibo) {
		this.iddetalleRecibo = iddetalleRecibo;
	}

	public Recibo getRecibo() {
		return this.recibo;
	}

	public void setRecibo(Recibo recibo) {
		this.recibo = recibo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public double getImporte() {
		return this.importe;
	}

	public void setImporte(double importe) {
		this.importe = importe;
	}
	
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

}
