package dominio.dominio;

// Generated 08-ene-2009 19:15:20 by Hibernate Tools 3.2.4.CR1

import java.sql.Time;
import java.util.Date;

/**
 * HorarioId generated by hbm2java
 */
public class HorarioId implements java.io.Serializable {

	private String pista;
	private Date dia_hora;


	public HorarioId() {
	}

	public HorarioId(String pista, Date dia_hora) {
		this.pista = pista;
		this.dia_hora = dia_hora;

	}
	
	public HorarioId(Date dia_hora) {
		this.dia_hora = dia_hora;

	}

	public String getPista() {
		return this.pista;
	}

	public void setPista(String pista) {
		this.pista = pista;
	}

	public Date getDia_hora() {
		return this.dia_hora;
	}

	public void setDia_hora(Date dia_hora) {
		this.dia_hora = dia_hora;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HorarioId))
			return false;
		HorarioId castOther = (HorarioId) other;

		return ((this.getPista() == castOther.getPista()) || (this.getPista() != null
				&& castOther.getPista() != null && this.getPista().equals(
				castOther.getPista())))
				&& ((this.getDia_hora() == castOther.getDia_hora()) || (this.getDia_hora() != null
						&& castOther.getDia_hora() != null && this.getDia_hora().equals(
						castOther.getDia_hora())));
				
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPista() == null ? 0 : this.getPista().hashCode());
		result = 37 * result
				+ (getDia_hora() == null ? 0 : this.getDia_hora().hashCode());
		
		return result;
	}

}
