package dominio.dominio;

// Generated 02-ene-2009 17:10:24 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pista generated by hbm2java
 */
public class Pista implements java.io.Serializable {

	private String nombre;
	private double precio;
	private Set horarios = new HashSet(0);

	public Pista() {
	}

	public Pista(String nombre, double precio) {
		this.nombre = nombre;
		this.precio = precio;
	}

	public Pista(String nombre, double precio, Set horarios) {
		this.nombre = nombre;
		this.precio = precio;
		this.horarios = horarios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

}
