package dominio.dominio;

// Generated 02-dic-2008 9:49:40 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * SocioFamiliar generated by hbm2java
 */
public class SocioFamiliar implements java.io.Serializable {

	private SocioFamiliarId id;
	private Socio socio;
	private Set recibos = new HashSet(0);
	private Set horarios = new HashSet(0);

	public SocioFamiliar() {
	}

	public SocioFamiliar(SocioFamiliarId id, Socio socio) {
		this.id = id;
		this.socio = socio;
	}

	public SocioFamiliar(SocioFamiliarId id, Socio socio, Set recibos,
			Set horarios) {
		this.id = id;
		this.socio = socio;
		this.recibos = recibos;
		this.horarios = horarios;
	}

	public SocioFamiliarId getId() {
		return this.id;
	}

	public void setId(SocioFamiliarId id) {
		this.id = id;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Set getRecibos() {
		return this.recibos;
	}

	public void setRecibos(Set recibos) {
		this.recibos = recibos;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

}
