package dominio.dominio;

// Generated 08-ene-2009 19:15:20 by Hibernate Tools 3.2.4.CR1

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

	private HorarioId id;
	private Cliente cliente;
	//private Pista pista;
	private double importe;
	private int pagado;

	public Horario() {
	}

	public Horario(HorarioId id, Cliente cliente, 
			double importe, int pagado) {
		this.id = id;
		this.cliente = cliente;
		//this.pista = pista;
		this.importe = importe;
		this.pagado = pagado;
	}

	public HorarioId getId() {
		return this.id;
	}

	public void setId(HorarioId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

//	public Pista getPista() {
//		return this.pista;
//	}
//
//	public void setPista(Pista pista) {
//		this.pista = pista;
//	}

	public double getImporte() {
		return this.importe;
	}

	public void setImporte(double importe) {
		this.importe = importe;
	}

	public int isPagado() {
		return this.pagado;
	}

	public void setPagado(int pagado) {
		this.pagado = pagado;
	}

}
