package dominio.dominio;

// Generated 08-ene-2009 19:15:20 by Hibernate Tools 3.2.4.CR1

/**
 * Personal generated by hbm2java
 */
public class Personal implements java.io.Serializable {

	private String usuario;
	private String clave;

	public Personal() {
	}

	public Personal(String usuario, String clave) {
		this.usuario = usuario;
		this.clave = clave;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
