package dominio.dominio;

// Generated 02-ene-2009 17:10:24 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SocioFamiliar generated by hbm2java
 */
public class SocioFamiliar implements java.io.Serializable {

	private SocioFamiliarId id;
	private Socio socio;
	private Set recibos = new HashSet(0);
	private Set horarios = new HashSet(0);

	public SocioFamiliar() {
	}

	public SocioFamiliar(Socio socio) {
		this.socio = socio;
	}

	public SocioFamiliar(Socio socio, Set recibos, Set horarios) {
		this.socio = socio;
		this.recibos = recibos;
		this.horarios = horarios;
	}

	public SocioFamiliarId getId() {
		return this.id;
	}

	public void setId(SocioFamiliarId id) {
		this.id = id;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Set getRecibos() {
		return this.recibos;
	}

	public void setRecibos(Set recibos) {
		this.recibos = recibos;
	}

	public Set getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set horarios) {
		this.horarios = horarios;
	}

}
