package dominio.dominio;

// Generated 08-ene-2009 19:15:20 by Hibernate Tools 3.2.4.CR1

/**
 * SocioFamiliarId generated by hbm2java
 */
public class SocioFamiliarId implements java.io.Serializable {

	private String dni;
	private int codSocio;

	public SocioFamiliarId() {
	}

	public SocioFamiliarId(String dni, int codSocio) {
		this.dni = dni;
		this.codSocio = codSocio;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public int getCodSocio() {
		return this.codSocio;
	}

	public void setCodSocio(int codSocio) {
		this.codSocio = codSocio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SocioFamiliarId))
			return false;
		SocioFamiliarId castOther = (SocioFamiliarId) other;

		return ((this.getDni() == castOther.getDni()) || (this.getDni() != null
				&& castOther.getDni() != null && this.getDni().equals(
				castOther.getDni())))
				&& (this.getCodSocio() == castOther.getCodSocio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37 * result + this.getCodSocio();
		return result;
	}

}
