package dominio.dominio;

// Generated 02-dic-2008 9:49:40 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	private SocioId id;
	private Cliente cliente;
	private Date fechaIngreso;
	private double cuota;
	private int numeroMiembros;
	private String cuentaBanco;
	private Set socioFamiliars = new HashSet(0);

	public Socio() {
	}

	public Socio(SocioId id, Cliente cliente, Date fechaIngreso, double cuota,
			int numeroMiembros, String cuentaBanco) {
		this.id = id;
		this.cliente = cliente;
		this.fechaIngreso = fechaIngreso;
		this.cuota = cuota;
		this.numeroMiembros = numeroMiembros;
		this.cuentaBanco = cuentaBanco;
	}

	public Socio(SocioId id, Cliente cliente, Date fechaIngreso, double cuota,
			int numeroMiembros, String cuentaBanco, Set socioFamiliars) {
		this.id = id;
		this.cliente = cliente;
		this.fechaIngreso = fechaIngreso;
		this.cuota = cuota;
		this.numeroMiembros = numeroMiembros;
		this.cuentaBanco = cuentaBanco;
		this.socioFamiliars = socioFamiliars;
	}

	public SocioId getId() {
		return this.id;
	}

	public void setId(SocioId id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public double getCuota() {
		return this.cuota;
	}

	public void setCuota(double cuota) {
		this.cuota = cuota;
	}

	public int getNumeroMiembros() {
		return this.numeroMiembros;
	}

	public void setNumeroMiembros(int numeroMiembros) {
		this.numeroMiembros = numeroMiembros;
	}

	public String getCuentaBanco() {
		return this.cuentaBanco;
	}

	public void setCuentaBanco(String cuentaBanco) {
		this.cuentaBanco = cuentaBanco;
	}

	public Set getSocioFamiliars() {
		return this.socioFamiliars;
	}

	public void setSocioFamiliars(Set socioFamiliars) {
		this.socioFamiliars = socioFamiliars;
	}

}
